package fortune

import (
	"math/rand"
)

// Funny, nerdy developer fortunes crossing coding, DSA, and Anime (exactly 256 items)
var fortunesList = []string{
	// Jujutsu Kaisen (JJK)
	"Like Gojo, you will say 'Nah, I'd compile'. And then it crashes.",
	"Your recursive function will trigger domain expansion: Infinite Loop.",
	"Your Reverse Cursed Technique is just restoring from a git stash.",
	"Your code has more binding vows than Sukuna just to compile.",
	"Toji Fushiguro behavior: Zero cursed energy, zero memory allocation, pure speed.",
	"Your garbage collector has less output than Megumi's shadows.",
	"You will debug your code and realize Sukuna is living rent-free in your heap.",
	"Your space complexity has no limit, just like Gojo's Limitless.",
	"Your codebase is like Yuji eating Sukuna's fingers: a terrible decision that somehow works.",
	"Megumi summoning Mahoraga is you opening Stack Overflow at 3 AM.",
	"Your infinite loop is Gojo's Unlimited Void.",
	"Domain Expansion: Heap Overflow.",
	"Domain Expansion: Null Pointer Sanctuary.",
	"Your code is like Gojo in the box: sealed and never getting executed.",
	"Like Nanami, you will work overtime because someone committed to main.",
	"Your local environment is Gojo's hollow purple: it deletes everything.",
	"Like Sukuna's domain, your query will slice the database into tiny pieces.",
	"Your unit tests are like Panda: not actually a panda, and not actually working.",
	"You will write a function so cursed it needs a Grade 1 Sorcerer to debug.",
	"Your error handler is like Mahoraga: it adapts to every exception until it dies.",

	// Naruto
	"Your variable names are so bad, even the Sharingan can't read them.",
	"May your recursion not trap you in the Infinite Tsukuyomi.",
	"Your garbage collector works harder than the entire squad in Naruto.",
	"Your Git tree is more tangled than the timeline of Steins;Gate.",
	"Your database query is slower than the 5 minutes left on Planet Namek.",
	"Your senior dev is like Kakashi: always late to your PR reviews.",
	"Your binary tree is unbalanced, like Sasuke's family relationships.",
	"Like Tanjiro, you must breathe deeply before viewing legacy code.",
	"Your css is like a Genjutsu: looks good until you break the illusion.",
	"Your code is like Naruto's clone jutsu: memory is full and they all do nothing.",
	"You will try to optimize a loop and end up crying like Deku.",
	"Your production crash is like Pain destroying Konoha in one click.",
	"Your code has more fillers than Naruto Shippuden.",
	"Like Rock Lee, you will drop the weights and write raw assembly.",
	"Your git branch is like Orochimaru: keeps changing bodies to survive.",
	"Your codebase has more legacy curses than the Uchiha clan.",
	"May your API requests find their path like Naruto tracking Sasuke.",
	"Your recursive stack is like Itachi's Tsukuyomi: 72 hours of pain in 1ms.",
	"Like Jiraiya, your favorite code is written on paper in a bathhouse.",
	"Your database index is like Neji's Byakugan: sees everything except the blind spot.",
	"You will write a script that replicates itself like a Shadow Clone memory leak.",
	"Like Guy Sensei, you will open the 8th Gate of CPU usage.",
	"Your code is like Sakura in early Naruto: completely useless but always present.",
	"You will search for a bug like Naruto searching for Sasuke: endless and painful.",
	"Your refactoring is like Obito's Kamui: it sends code into another dimension.",

	// One Piece
	"Your variables are like Zoro: completely lost in the scope.",
	"You will implement a hash map and call it Gomu Gomu no Hash.",
	"Like Lelouch, you command your bugs to disappear. They won't.",
	"Your pull request will search for the One Piece: it does not exist.",
	"Your Gear 5 code is laughing while the CPU is crying.",
	"Your code path is like Zoro's directions: leads to a SegFault.",
	"Your database query is crossing the Grand Line without a log pose.",
	"Like Sanji, you will simp for a framework that doesn't care about you.",
	"Your server bandwidth is like Luffy's appetite: completely bottomless.",
	"Your codebase has more holes than Portgas D. Ace. Too soon?",
	"Like Nami, you will charge the client for every single character typed.",
	"Your compiler has less Haki than a minor side character.",
	"Your Git commit messages are like the Void Century: completely erased.",
	"You will debug a legacy function and feel like you're translating Poneglyphs.",
	"Your microservices are like the Straw Hat crew: scattered across the cloud.",
	"Like Usopp, you will lie about the progress of your sprint task.",
	"Your legacy database is like the Florian Triangle: queries go in, nothing comes out.",
	"Your CSS grid layout is like the Red Line: blocking all movement.",
	"Like Chopper, your error logger tries its best but is just cute.",
	"Your code is like Brook: already dead, but still running.",
	"You will name a variable 'JoyBoy' and it will disappear for 800 lines.",
	"Like Whitebeard, you will stand tall while your production server collapses.",
	"Your API response is like the Wano Arc: takes 200 episodes to finish.",
	"Your loop is like the Grand Line: once you enter, there is no exit.",
	"Like Nico Robin, you want to live... but the legacy code says no.",

	// Dragon Ball
	"A wild SegFault approaches! It has a power level over 9000.",
	"Your memory leak is bigger than the Colossal Titan.",
	"Your code quality is giving Yamcha dying in a crater vibes.",
	"Like Saitama, you will solve the bug with exactly one keystroke.",
	"Like Ryuk, the compiler loves watching you struggle for entertainment.",
	"Your code has more plot holes than the ending of Bleach.",
	"Your database migration takes longer than Goku charging a Spirit Bomb.",
	"Your CPU temperature will go Super Saiyan 3 today.",
	"Your code optimization is like Frieza's transformations: looks different, still bad.",
	"Like Vegeta, your pride will be destroyed by a minor compiler warning.",
	"Your code is like Shenron: only works if you find seven missing imports.",
	"Your application speed is like DBZ filler: absolutely nothing happens for 10 runs.",
	"You will write a function so heavy it requires 100g gravity to run.",
	"Like Piccolo, you will stand in the corner and judge the junior dev's code.",
	"Your bug is like Cell: every time you patch it, it absorbs another module.",
	"Your unit tests are like Krillin: they die in every single run.",
	"Like Gotenks, your code is fused together and expires in 30 minutes.",
	"Your server load is like Majin Buu: absorbs all resources and turns them to trash.",
	"Your recursion depth is over 9000! Stack overflow.",
	"Like Whis, you will watch your server crash and do nothing because you're neutral.",
	"Your code is like the Hyperbolic Time Chamber: 1 minute of running feels like a year.",
	"You will try to merge branches and trigger a fusion dance failure.",
	"Your documentation is like Gohan's potential: highly talked about, never seen.",
	"Like Master Roshi, you will get distracted by a package's pretty UI.",
	"Your database query will take longer than the destruction of Planet Namek.",

	// Death Note
	"You will debug with the intensity of Light Yagami writing in his note.",
	"Your compiler is a tsundere: 'It's not like I compiled this for you!'",
	"Like L, you will sit weirdly in your chair because it increases debugging IQ.",
	"You will write code that deletes files like Light deleting criminals.",
	"Your git log is like the Death Note: contains a list of dead code.",
	"Like Ryuk, you will eat apples while watching your code burn.",
	"Your variable naming style is like Kira's identity: hidden behind 10 layers.",
	"You will find a bug and declare: 'I will take a potato chip... AND EAT IT!'",
	"Your code is like L's real name: unknown and impossible to find.",
	"Like Near, you will play with toys instead of writing unit tests.",
	"Your debug print statements are like Kira's messages: trying to confuse the cops.",
	"Your query will execute exactly as planned, just like Light's schemes.",
	"Your codebase has more sacrifices than the task force.",
	"Like Misa Misa, you will blindly follow a framework without understanding it.",
	"Your algorithm is like L's deduction: complex, brilliant, and ignored.",

	// Attack on Titan (AoT)
	"Like Eren Jaeger, you will keep moving forward... to write more bugs.",
	"Your PR is like an anime adaptation: completely ignores the source.",
	"May your production deploy not trigger the Third Impact.",
	"Like Levi, you will spend all day cleaning up dirty code.",
	"Your wall of code will fall like Wall Maria to a single syntax error.",
	"Your microservices are like the Rumbling: flatting your server infrastructure.",
	"Your code has less freedom than Eren Jaeger.",
	"Like Armin, you believe talking to the compiler will resolve the conflict.",
	"Your memory consumption is like the Colossal Titan: giant and steaming.",
	"Your compiler warnings are like Titans: ignore them and they will eat you.",
	"Like Hange, you will get way too excited about a weird bug.",
	"Your git push is like the Scout Regiment: high mortality rate.",
	"Your code is like Reiner: keeps trying to crash but somehow survives.",
	"Your debugging session will feel like the Battle of Shiganshina.",
	"Like Sasha, you only care about the potato in your console log.",
	"Your code is like the Beast Titan: throwing rocks at your other modules.",
	"You will build a wall of nested try-catches to protect your app.",
	"Your recursive depth is like the basement: takes 3 seasons to reach.",
	"Like Mikasa, you are obsessed with one specific variable.",
	"Your codebase is like Marley: full of propaganda and ancient history.",

	// Demon Slayer
	"Like Tanjiro, you must breathe deeply before looking at legacy code.",
	"You will fix a bug and feel like you solved the Millennium Puzzle.",
	"Your code is like Nezuko: quiet, boxed up, and highly dangerous.",
	"Like Zenitsu, your code only works when the thread is asleep.",
	"Your pointer variable is like Inosuke: wild, untyped, and running anywhere.",
	"Your bug is like Muzan: changes form every time you try to locate it.",
	"You will use Water Breathing: First Form to debug a memory leak.",
	"Like the Hashira, your modules will fall one by one in production.",
	"Your code is like Muzan's blood: too much of it will kill the project.",
	"Your git merge conflict is like a battle with an Upper Moon.",
	"Like Genya, your code consumes other languages to run.",
	"Your documentation is like the Hinokami Kagura: ancient and hard to master.",
	"Your compiler error is like Nezuko's muzzle: keeps it from screaming.",
	"Your testing suite is like the Final Selection: almost nothing survives.",
	"Like Giyu, you have no friends in the workspace slack channel.",

	// Neon Genesis Evangelion
	"Your code is like Shinji: get in the loop, or get out.",
	"Your deploy will cause the Third Impact in the production environment.",
	"Your compiler protection is like an AT Field: keeps bugs from entering.",
	"Like Asuka, your code will scream 'ANTA BAKA!' at the compiler.",
	"Your app is like EVA-01: goes berserk when the battery drops to 0.",
	"Like Rei Ayanami, your variables are easily replaced by clones.",
	"Your debug console is like the MAGI system: three units disagreeing.",
	"Your memory allocation is like the LCL fluid: smells like blood.",
	"Like Gendo Ikari, you have a grand plan that involves destroying everything.",
	"Your project timeline is like the Human Instrumentality Project: messy.",
	"Your build script is like an Angel: attacks your system without warning.",
	"Your code is like Shinji's social life: full of panic and isolation.",
	"You will stare at your code and say: 'I'm so messed up.'",
	"Your CPU is screaming like EVA-02 in the movie.",
	"Like Seele, your project managers are just monolithic stone tablets.",

	// JoJo's Bizarre Adventure
	"Your stand is 'Za Warudo': pauses the execution thread for 9 seconds.",
	"Your code refactoring is like Diavolo's King Crimson: skips the logic.",
	"Like Dio, your code will declare: 'You thought it was a feature, but it was me, DIO!'",
	"Your debugger will shout 'MUDA MUDA MUDA' at your breakpoints.",
	"Your variable is like Joseph Joestar: next line is already predicted.",
	"Your git commit history is a Bizarre Adventure.",
	"Your code is like Killer Queen: touches a database and explodes.",
	"Like Jotaro, you will say 'Yare Yare Daze' before opening main.go.",
	"Your bug is like Yoshikage Kira: just wants a quiet life in production.",
	"Your compiler is like Rohan Kishibe: inspects your code's memory directly.",
	"Your garbage collector is like Okuyasu's The Hand: deletes memory spaces.",
	"Like Bruno Bucciarati, you can taste if a variable is lying.",
	"Your multithreading is like Star Platinum: punches 1000 times per second.",
	"Your loop is like Gold Experience Requiem: you will never reach the truth (exit).",
	"Like Giorno Giovanna, you have a dream of writing bug-free code.",
	"Your server is like Iggy: eats coffee gum and farts on your queries.",
	"Your database is like Dio's coffin: locked for 100 years.",
	"Your code path is like Steel Ball Run: long, dusty, and full of horses.",
	"Like Kars, your code will eventually stop thinking.",
	"Your styling sheet is like Rohan's outfits: highly fashionable and weird.",

	// My Hero Academia (MHA)
	"Like Deku, your code will break its own bones just to run.",
	"Your queries are like Bakugo: loud, explosive, and full of rage.",
	"Your server capacity is like All Might: only works for 3 hours a day.",
	"Your system quirk is: allocating memory that cannot be freed.",
	"Like Todoroki, your code is half hot garbage, half cold frozen threads.",
	"Your bug is like All For One: steals methods from other classes.",
	"Your code will shout 'PLUS ULTRA' and consume 100% CPU.",
	"Like Uraraka, your variables will float out of scope.",
	"Your validation script is like Eraser Head: erases all quirks/inputs.",
	"Like Mineta, your code is sticky, annoying, and shouldn't be there.",
	"Your staging server is like UA High: constantly under attack.",
	"Your database is like All Might's true form: skinny, weak, and coughing blood.",
	"Your code is like Iida: runs fast but is way too strict about rules.",
	"Like Tsuyu, your code is clean and handles wet inputs well.",
	"Your refactoring will feel like Deku's training arc: painful and slow.",

	// Hunter x Hunter (HxH)
	"Your pointer contract is like Gon's Nen contract: gives power now, destroys memory later.",
	"Your server speed is like Killua's Godspeed: lightning fast until it runs out.",
	"Your code is like Hisoka: creeping on your private variables.",
	"Your bug is like a Chimera Ant: evolves every time you run a test.",
	"Like Kurapika, your code is chained to one specific framework.",
	"Your database is like Greed Island: expensive, complex, and hard to exit.",
	"Your logic has more rules than Kurapika's Emperor Time.",
	"Like Leorio, your code is loud, wears a suit, and accomplishes nothing.",
	"Your memory allocation is like Nen: requires intense focus to control.",
	"Your unit tests are like the Hunter Exam: 99% fail rate.",
	"Like Netero, you will pray 10,000 times before compiling.",
	"Your microservices are like the Phantom Troupe: rogue and dangerous.",
	"Your loop is like the Dark Continent: unexplored and full of terrors.",
	"Like Killua's needles, someone left a hidden check that alters execution.",
	"Your code has less progression than the HxH manga schedule.",

	// Steins;Gate
	"Your Git timeline has more branches than Steins;Gate.",
	"Your error message is like a D-Mail: sent to the past to break the build.",
	"Like Okabe, you will scream 'El Psy Kongroo' when the test passes.",
	"Your local server is like the PhoneWave (name subject to change).",
	"Your code is like Mayuri's pocket watch: it just stopped working.",
	"Like Kurisu, your compiler is a tsundere assistant.",
	"Your database backup is like reading memory across alpha worldlines.",
	"Your application is heading toward the beta worldline (production crash).",
	"Your code has more paranoia than Hououin Kyouma.",
	"Like Daru, you are the super hacker carrying the entire project.",

	// Sword Art Online (SAO)
	"Your code is like SAO: if it crashes in production, you die in real life.",
	"Like Kirito, you will dual-wield packages to solve a basic problem.",
	"Your microservice is like Asuna: carrying your slow backend.",
	"Your server is like Aincrad: 100 floors of legacy architecture.",
	"Your login session is like SAO: there is no log out button.",
	"Like Klein, your variables are always single and waiting.",
	"Your bug is like the Gleam Eyes: destroys your stack trace.",
	"Your testing environment is like the Safe Zone: bugs are hidden.",
	"Like Yui, your debugging assistant is an AI that calls you papa.",
	"Your code is like Kirito's plot armor: survives despite zero logic.",

	// One Punch Man
	"Like Saitama, you solve the bug with one keystroke (deleting the file).",
	"Your server cooling system is like Genos: constantly self-destructing.",
	"Your code quality is like King: looks threatening, actually useless.",
	"Your test suite is like Saitama's training: 100 lines of code, 100 tests, every day.",
	"Your compiler error is like Boros: takes multiple forms before dying.",
	"Like Mumen Rider, your code tries its best but gets crushed immediately.",
	"Your database is like the Hero Association: corrupt and disorganized.",
	"Your execution speed is like Sonic: fast but hits a wall.",
	"Your bug is like Saitama's mosquito: impossible to hit.",
	"Your variable naming is like Kira: hidden behind a fake name.",
}

// GetRandomFortune returns a random Gen Z developer fortune cookie
func GetRandomFortune() string {
	if len(fortunesList) == 0 {
		return "Keep coding."
	}
	return fortunesList[rand.Intn(len(fortunesList))]
}
